"""empty message

Revision ID: 16161cdcfb42
Revises: 47820aefbcfa
Create Date: 2020-02-17 04:30:35.560701

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16161cdcfb42'
down_revision = '47820aefbcfa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sample',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sample')
    # ### end Alembic commands ###
